# Generated by Django 4.1.1 on 2022-09-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=230)),
                ('about_me', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=230)),
                ('full_adders', models.CharField(blank=True, max_length=150, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('freelance', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unvailable', 'Unvailable')], default='Available', max_length=13, null=True)),
                ('profile_pictuer', models.ImageField(upload_to='profile/')),
                ('cover_picture', models.ImageField(upload_to='coverpictue/')),
                ('faceboock_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('skype', models.URLField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AboutMe',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('meassage', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_project', models.IntegerField(blank=True, null=True)),
                ('hours_of_support', models.IntegerField(blank=True, null=True)),
                ('awards', models.IntegerField(blank=True, null=True)),
                ('happy_clients', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Counts',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lavel', models.CharField(max_length=150)),
                ('campus_name', models.CharField(max_length=220)),
                ('year', models.CharField(max_length=10)),
                ('details', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=220)),
                ('year', models.CharField(max_length=10)),
                ('lavel_1', models.CharField(blank=True, max_length=250, null=True)),
                ('lavel_2', models.CharField(blank=True, max_length=250, null=True)),
                ('lavel_3', models.CharField(blank=True, max_length=250, null=True)),
                ('lavel_4', models.CharField(blank=True, max_length=250, null=True)),
                ('lavel_5', models.CharField(blank=True, max_length=250, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('sort_description', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='service_img')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Skill_name', models.CharField(blank=True, max_length=25)),
                ('Skill_percentage', models.IntegerField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='TESTIMONIALS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['create'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('full_catefory_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Client_adderss', models.CharField(blank=True, max_length=100, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='portfolio_img')),
                ('details', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('pro_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.portfolio_category')),
            ],
        ),
        migrations.CreateModel(
            name='Extera_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('eimage', models.ImageField(blank=True, upload_to='product_pic/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.portfolio')),
            ],
        ),
    ]
