# Generated by Django 4.1 on 2022-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_education_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=220)),
                ('year', models.CharField(max_length=10)),
                ('lavel_1', models.CharField(blank=True, max_length=200, null=True)),
                ('lavel_2', models.CharField(blank=True, max_length=200, null=True)),
                ('lavel_3', models.CharField(blank=True, max_length=200, null=True)),
                ('lavel_4', models.CharField(blank=True, max_length=200, null=True)),
                ('lavel_5', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(default='timezone', upload_to='service_img'),
            preserve_default=False,
        ),
    ]
