# Generated by Django 4.1 on 2022-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_testimonials_create_alter_testimonials_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['create'], 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='testimonials',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
