# Generated by Django 4.1 on 2022-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_testimonials_options_testimonials_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_project', models.IntegerField(blank=True, null=True)),
                ('hours_of_support', models.IntegerField(blank=True, null=True)),
                ('awards', models.IntegerField(blank=True, null=True)),
                ('happy_clients', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Counts',
                'ordering': ['create_at'],
            },
        ),
    ]
