# Generated by Django 4.1 on 2022-09-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='counts',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
